In [119]:
import requests 
import pandas as pd
from pandas.io.json import json_normalize
import json

In [152]:
df = pd.read_json('https://api.themoviedb.org/3/movie/top_rated?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US&page=1')
dfTR = pd.read_json('http://api.themoviedb.org/3/discover/movie?certification_country=US&certification=R&sort_by=vote_average.desc&api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US&page=1')

In [161]:
dfTR2 = json_normalize(df['results'])
result2 = pd.concat([dfTR,dfTR2], axis=1).drop('results',axis=1)

In [166]:

df2 = json_normalize(df['results'])
result = pd.concat([df, df2], axis=1).drop('results', axis=1)
result2

,page,total_results,total_pages,popularity,vote_count,video,poster_path,id,adult,backdrop_path,original_language,original_title,genre_ids,title,vote_average,overview,release_date
0,1,10000,500,17.437,2214,False,/2CAL2433ZeIihfX1Hb2139CX0pW.jpg,19404,False,/pVGzV02qmHVoKx9ehBNy7m2u5fs.jpg,hi,दिलवाले दुल्हनिया ले जायेंगे,"[35, 18, 10749]",Dilwale Dulhania Le Jayenge,8.8,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20
1,1,10000,500,35.028,15042,False,/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg,278,False,/65nAfGikljrOkfIrcfmrNTJTAXF.jpg,en,The Shawshank Redemption,"[18, 80]",The Shawshank Redemption,8.7,Framed in the 1940s for the double murder of h...,1994-09-23
2,1,10000,500,29.433,11480,False,/d4KNaTrltq6bpkFS01pYtyXa09m.jpg,238,False,/6xKCYgH16UuwEGAyroLU6p8HLIn.jpg,en,The Godfather,"[80, 18]",The Godfather,8.7,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14
3,1,10000,500,176.819,4728,False,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,496243,False,/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg,ko,기생충,"[35, 18, 53]",Parasite,8.6,"All unemployed, Ki-taek's family takes peculia...",2019-05-30
4,1,10000,500,19.641,9161,False,/yPisjyLweCl1tbgwgtzBCNCBle.jpg,424,False,/cTNYRUTXkBgPH3wP3kmPUB5U6dA.jpg,en,Schindler's List,"[18, 36, 10752]",Schindler's List,8.6,The true story of how businessman Oskar Schind...,1993-11-30
5,1,10000,500,22.280,6751,False,/bVq65huQ8vHDd1a4Z37QtuyEvpA.jpg,240,False,/gLbBRyS7MBrmVUNce91Hmx9vzqI.jpg,en,The Godfather: Part II,"[80, 18]",The Godfather: Part II,8.5,In the continuing saga of the Corleone crime f...,1974-12-20
6,1,10000,500,29.292,5012,False,/xq1Ugd62d23K2knRUx6xxuALTZB.jpg,372058,False,/7OMAfDJikBxItZBIug0NJig5DHD.jpg,ja,君の名は。,"[16, 18, 10749]",Your Name.,8.5,High schoolers Mitsuha and Taki are complete s...,2016-08-26
7,1,10000,500,47.471,8551,False,/oRvMaJOmapypFUcQqpgHMZA6qL9.jpg,129,False,/mnpRKVSXBX6jb56nabvmGKA0Wig.jpg,ja,千と千尋の神隠し,"[16, 14, 10751]",Spirited Away,8.5,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20
8,1,10000,500,20.562,9497,False,/sOHqdY1RnSn6kcfAHKu28jvTebE.jpg,497,False,/Rlt20sEbOQKPVjia7lUilFm49W.jpg,en,The Green Mile,"[14, 18, 80]",The Green Mile,8.5,A supernatural tale set on death row in a Sout...,1999-12-10
9,1,10000,500,28.749,17542,False,/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg,680,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,en,Pulp Fiction,"[80, 53]",Pulp Fiction,8.5,"A burger-loving hit man, his philosophical par...",1994-09-10
10,1,10000,500,19.398,8242,False,/f7DImXDebOs148U4uPjI61iDvaK.jpg,637,False,/bORe0eI72D874TMawOOFvqWS6Xe.jpg,it,La vita è bella,"[35, 18]",Life Is Beautiful,8.5,A touching story of an Italian book seller of ...,1997-12-20
11,1,10000,500,23.886,16928,False,/yE5d3BUhE8hCnkMUJOo1QDoOGNz.jpg,13,False,/tNVTWNa8cxZLw7aWvHzSDLyc7ig.jpg,en,Forrest Gump,"[35, 18, 10749]",Forrest Gump,8.4,A man with a low IQ has accomplished great thi...,1994-07-06
12,1,10000,500,29.006,21088,False,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,155,False,/hqkIcbrOHL86UncnHIsHVcVmzue.jpg,en,The Dark Knight,"[28, 80, 18, 53]",The Dark Knight,8.4,Batman raises the stakes in his war on crime. ...,2008-07-16
13,1,10000,500,31.551,14701,False,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,122,False,/8BPZO0Bf8TeAy8znF43z8soK3ys.jpg,en,The Lord of the Rings: The Return of the King,"[28, 12, 14]",The Lord of the Rings: The Return of the King,8.4,Aragorn is revealed as the heir to the ancient...,2003-12-01
14,1,10000,500,20.397,1727,False,/v6xrz4fr92KY1oNC3HsEvrsvR1n.jpg,346,False,/61vLiK96sbXeHpQiMxI4CuqBA3z.jpg,ja,七人の侍,"[28, 18]",Seven Samurai,8.4,A samurai answers a village's request for prot...,1954-04-26
15,1,10000,500,23.708,2669,False,/x733R4ISI0RbKeHhVkXdTMFmTFr.jpg,311,False,/vnT6HzjLSDrAweHn9xWykb8Ii6T.jpg,en,Once Upon a Time in America,"[18, 80]",Once Upon a Time in America,8.4,A former Prohibition-era Jewish gangster retur...,1984-05-23
16,1,10000,500,22.875,6731,False,/pwpGfTImTGifEGgLb3s6LRPd4I6.jpg,769,False,/sw7mordbZxgITU877yTpZCud90M.jpg,en,GoodFellas,"[18, 80]",GoodFellas,8.4,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12
17,1,10000,500,9.056,568,False,/imcOp1kJsCsAFCoOtY5OnPrFbAf.jpg,40096,False,/alQqTpmEkxSLgajfEYTsTH6nAKB.jpg,pt,O Auto da Compadecida,"[12, 35]",A Dog's Will,8.4,The lively João Grilo and the sly Chicó are po...,2000-09-15
18,1,10000,500,20.776,5790,False,/81d8oyEFgj7FlxJqSDXWr8JH8kV.jpg,539,False,/3md49VBCeqY6MSNyAVY6d5eC6bA.jpg,en,Psycho,"[18, 27, 53]",Psycho,8.4,When larcenous real estate clerk Marion Crane ...,1960-06-22
19,1,10000,500,20.490,4362,False,/3W0v956XxSG5xgm7LB6qu8ExYJ2.jpg,389,False,/lH2Ga8OzjU1XlxJ73shOlPx6cRw.jpg,en,12 Angry Men,[18],12 Angry Men,8.4,The defense and the prosecution have rested an...,1957-04-10

In [230]:
id_by_movie = result2.groupby("original_title")['title','id','original_language'].head()
id_by_movie

                                            title      id original_language
0                     Dilwale Dulhania Le Jayenge   19404                hi
1                        The Shawshank Redemption     278                en
2                                   The Godfather     238                en
3                                        Parasite  496243                ko
4                                Schindler's List     424                en
5                          The Godfather: Part II     240                en
6                                      Your Name.  372058                ja
7                                   Spirited Away     129                ja
8                                  The Green Mile     497                en
9                                    Pulp Fiction     680                en
10                              Life Is Beautiful     637                it
11                                   Forrest Gump      13                en
12                                The Dark Knight     155                en
13  The Lord of the Rings: The Return of the King     122                en
14                                  Seven Samurai     346                ja
15                    Once Upon a Time in America     311                en
16                                     GoodFellas     769                en
17                                   A Dog's Will   40096                pt
18                                         Psycho     539                en
19                                   12 Angry Men     389                en

In [170]:
idls = list(result['id'])

In [171]:
idls

[19404,
 278,
 238,
 496243,
 424,
 240,
 372058,
 129,
 497,
 680,
 637,
 13,
 155,
 122,
 346,
 311,
 769,
 40096,
 539,
 389]

In [173]:
imdb_ids = []
for x in idls:
    movie_url = 'https://api.themoviedb.org/3/movie/' + str(x) +'?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US'
    imdb_ids.append(movie_url)

In [174]:
imdb_ids

['https://api.themoviedb.org/3/movie/19404?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/278?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/238?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/496243?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/424?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/240?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/372058?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/129?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/497?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/680?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/637?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/13?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/155?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/122?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/346?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/311?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/769?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/40096?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/539?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US',
 'https://api.themoviedb.org/3/movie/389?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US']

In [175]:
url = 'https://api.themoviedb.org/3/movie/19404?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US'


headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:73.0) Gecko/20100101 Firefox/73.0'
}
movie_resp = requests.get(url, headers=headers)
# movie_json = movie_resp.json()
# imdb_ids.append(movie_json['imdb_id']) # you won't use this

In [224]:
mrd

{'adult': False,
 'backdrop_path': '/pVGzV02qmHVoKx9ehBNy7m2u5fs.jpg',
 'belongs_to_collection': None,
 'budget': 13200000,
 'genres': [{'id': 35, 'name': 'Comedy'},
  {'id': 18, 'name': 'Drama'},
  {'id': 10749, 'name': 'Romance'}],
 'homepage': '',
 'id': 19404,
 'imdb_id': 'tt0112870',
 'original_language': 'hi',
 'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
 'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
 'popularity': 17.437,
 'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
 'production_companies': [{'id': 1569,
   'logo_path': '/lvzN86o3jrP44DIvn4SMBLOl9PF.png',
   'name': 'Yash Raj Films',
   'origin_country': 'IN'}],
 'production_countries': [{'iso_3166_1': 'IN', 'name': 'India'}],
 'release_date': '1995-10-20',
 'revenue': 100000000,
 'runtime': 190,
 'spoken_languages': [{'iso_639_1': 'hi', 'name': 'हिन्दी'}],
 'status': 'Released',
 'tagline': 'Come Fall In love, All Over Again..',
 'title': 'Dilwale Dulhania Le Jayenge',
 'video': False,
 'vote_average': 8.8,
 'vote_count': 2214}

In [254]:
# imdb_ids = []
# for x in idls:
#     movie_url = 'https://api.themoviedb.org/3/movie/' + str(x) +'?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US'
#     imdb_ids.append(movie_url)
# imdb_ids 
# url = 'https://api.themoviedb.org/3/movie/19404?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US'
# movie_resp = requests.get(url, headers=headers)
# mrd = movie_resp.json()
sample_id = 475303
for x in imdb_ids:
    
    def get_genre_and_PC(x):
        movie_url = 'https://api.themoviedb.org/3/movie/' + str(x) +'?api_key=d34a7ae8e00fac4590a4aee2a6e5d4a5&language=en-US'
#     for x in ids:
        movie_resp2 = requests.get(movie_url, headers=headers)
        mrd2 = movie_resp2.json()
        for p in mrd2['production_companies']:  
# mrd['genres'][2]['name']
                print(p['name'])
        for z in mrd2['genres']:
                print(z['name'])
   

get_genre_and_PC(sample_id)

Gravier Productions
Perdido Productions
FilmNation Entertainment
Comedy
Romance